name: "Test"
on: [push]
jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - name: echo
        id: step_two
        env:
          test_secret: ${{ secrets.DLI_SECRET }}
        if: ${{ env.test_secret == 'NotASecret' }}
        run: |
          echo "SECRETS!!"
